# Generated by Django 2.1.2 on 2018-10-15 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='Imagem'),
        ),
    ]
