# Generated by Django 2.1.2 on 2018-10-15 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0002_beer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='cervejas/', verbose_name='Imagem'),
        ),
    ]
