# Generated by Django 2.1.2 on 2018-10-15 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0003_auto_20181015_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='abv',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Alcohol By Volume'),
        ),
    ]
