# Generated by Django 2.1.2 on 2018-11-12 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0006_auto_20181112_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='beer',
            name='final_gravity',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Gravidade Final'),
        ),
        migrations.AddField(
            model_name='beer',
            name='original_gravity',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Gravidade Inicial'),
        ),
    ]
