# Generated by Django 2.1.2 on 2018-11-12 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beer', '0007_auto_20181112_0247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beer',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='beer.Category'),
        ),
        migrations.AlterField(
            model_name='beer',
            name='style',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='beer.Style'),
        ),
    ]
